package htw.common.enums;

public enum ElementTarget {
	PAGES_COUNT,
	PAGE_URL_BY_NUMBER,
	PAGES_DETAIL_URLS,
	ARTICLES_DATA_DELIMITER,
	ARTICLE_BRAND,
	ARTICLE_DESCRIPTION,
	ARTICLE_PRICE,
	ARTICLE_COLOR,
	ARTICLE_SIZES,
	ARTICLE_IMAGES
}
